-- 0. PROFILES (Sync with Supabase Auth)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  first_name text,
  last_name text,
  role text default 'member',
  updated_at timestamp with time zone
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

-- Drop existing policies if rebuilding to avoid conflicts
drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Users can insert their own profile." on profiles;
drop policy if exists "Users can update own profile." on profiles;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Function to handle new user signup with Auto-Avatar logic
create or replace function public.handle_new_user()
returns trigger as $$
declare
  default_avatar text;
begin
  -- Generate avatar URL if none provided
  if new.raw_user_meta_data->>'avatar_url' is null or new.raw_user_meta_data->>'avatar_url' = '' then
    default_avatar := 'https://ui-avatars.com/api/?background=c26d53&color=fff&name=' || replace(coalesce(new.raw_user_meta_data->>'full_name', 'User'), ' ', '+');
  else
    default_avatar := new.raw_user_meta_data->>'avatar_url';
  end if;

  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', 'New Member'), 
    default_avatar
  )
  on conflict (id) do nothing; -- Prevent crashing if profile exists
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 1. CLUBS
create table if not exists clubs (
  club_id bigint generated by default as identity primary key,
  name text not null,
  description text,
  privacy text default 'public', -- 'public' or 'private'
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text,
  category text
);

-- 2. BOOKS
create table if not exists books (
  book_id bigint generated by default as identity primary key,
  title text not null,
  author text,
  isbn text,
  language text,
  published_year int,
  cover_image_url text
);

-- 3. CLUB MEMBERS (Linking Users to Clubs)
create table if not exists club_members (
  club_member_id bigint generated by default as identity primary key,
  club_id bigint references clubs(club_id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  role text default 'member',
  member_status text default 'active',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(club_id, user_id)
);

-- 4. CLUB READS (Books assigned to a club)
create table if not exists club_reads (
  club_read_id bigint generated by default as identity primary key,
  club_id bigint references clubs(club_id) on delete cascade,
  book_id bigint references books(book_id) on delete cascade,
  status text default 'planned',
  start_date date,
  end_date date
);

-- 5. READING PROGRESS
create table if not exists reading_progress (
  progress_id bigint generated by default as identity primary key,
  club_read_id bigint references club_reads(club_read_id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  progress_type text default 'page',
  progress_value decimal default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(club_read_id, user_id)
);

-- 6. DISCUSSION THREADS
create table if not exists discussion_threads (
  thread_id bigint generated by default as identity primary key,
  club_id bigint references clubs(club_id) on delete cascade,
  club_read_id bigint references club_reads(club_read_id),
  created_by uuid references public.profiles(id),
  title text not null,
  is_pinned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. THREAD COMMENTS
create table if not exists thread_comments (
  comment_id bigint generated by default as identity primary key,
  thread_id bigint references discussion_threads(thread_id) on delete cascade,
  user_id uuid references public.profiles(id),
  parent_comment_id bigint references thread_comments(comment_id),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  is_deleted boolean default false
);

-- 8. EVENTS
create table if not exists events (
  event_id bigint generated by default as identity primary key,
  club_id bigint references clubs(club_id) on delete cascade,
  created_by uuid references public.profiles(id),
  title text not null,
  description text,
  location_type text,
  location_details text,
  start_datetime timestamp with time zone,
  end_datetime timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. EVENT ATTENDEES
create table if not exists event_attendees (
  event_attendee_id bigint generated by default as identity primary key,
  event_id bigint references events(event_id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  rsvp_status text,
  responded_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(event_id, user_id)
);

-- --- RLS POLICIES ---

-- CLUBS
alter table clubs enable row level security;
drop policy if exists "Clubs are viewable by everyone" on clubs;
create policy "Clubs are viewable by everyone" on clubs for select using (true);
drop policy if exists "Authenticated users can create clubs" on clubs;
create policy "Authenticated users can create clubs" on clubs for insert with check (auth.role() = 'authenticated');

-- MEMBERS
alter table club_members enable row level security;
drop policy if exists "Members viewable by everyone" on club_members;
create policy "Members viewable by everyone" on club_members for select using (true);
drop policy if exists "Users can join clubs" on club_members;
create policy "Users can join clubs" on club_members for insert with check (auth.uid() = user_id);

-- BOOKS
alter table books enable row level security;
drop policy if exists "Books viewable by everyone" on books;
create policy "Books viewable by everyone" on books for select using (true);
drop policy if exists "Authenticated users can add books" on books;
create policy "Authenticated users can add books" on books for insert with check (auth.role() = 'authenticated');

-- CLUB READS
alter table club_reads enable row level security;
drop policy if exists "Club reads are viewable by everyone" on club_reads;
create policy "Club reads are viewable by everyone" on club_reads for select using (true);
drop policy if exists "Authenticated users can add club reads" on club_reads;
create policy "Authenticated users can add club reads" on club_reads for insert with check (auth.role() = 'authenticated');

-- READING PROGRESS
alter table reading_progress enable row level security;
drop policy if exists "Users can view own progress" on reading_progress;
create policy "Users can view own progress" on reading_progress for select using (auth.uid() = user_id);
drop policy if exists "Users can manage own progress" on reading_progress;
create policy "Users can manage own progress" on reading_progress for all using (auth.uid() = user_id);

-- DISCUSSIONS
alter table discussion_threads enable row level security;
drop policy if exists "Threads are viewable by everyone" on discussion_threads;
create policy "Threads are viewable by everyone" on discussion_threads for select using (true);
drop policy if exists "Authenticated users can create threads" on discussion_threads;
create policy "Authenticated users can create threads" on discussion_threads for insert with check (auth.role() = 'authenticated');

-- COMMENTS
alter table thread_comments enable row level security;
drop policy if exists "Comments are viewable by everyone" on thread_comments;
create policy "Comments are viewable by everyone" on thread_comments for select using (true);
drop policy if exists "Authenticated users can post comments" on thread_comments;
create policy "Authenticated users can post comments" on thread_comments for insert with check (auth.role() = 'authenticated');


-- --- SEED DATA (20 CLUBS) ---
-- Insert only if table is empty to avoid duplicates
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM clubs LIMIT 1) THEN
    INSERT INTO clubs (name, description, category, image_url, privacy) VALUES
    ('The African Classics', 'A deep dive into the foundational texts of modern African literature, from Achebe to Wa Thiong''o.', 'Fiction', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Lagos Bookworms', 'A community for readers in Lagos to meet, discuss, and share the joy of reading contemporary Nigerian fiction.', 'Fiction', 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Tech Titans Read', 'Discussing the latest in technology, AI, and startup culture. Books that shape the future.', 'Non-Fiction', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Pan-African History', 'Exploring the rich and complex history of the continent through rigorous historical texts and biographies.', 'History', 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('The Poetry Corner', 'For lovers of verse, rhyme, and rhythm. We explore contemporary and classical poets from around the world.', 'Poetry', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Sci-Fi & Fantasy Africa', 'Speculative fiction from an African perspective. Afrofuturism, magic realism, and beyond.', 'Fiction', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Women in Literature', 'Celebrating the voices of women authors across genres and generations.', 'Fiction', 'https://images.unsplash.com/photo-1470549638415-0a0755be0619?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Business & Strategy', 'Sharpen your mind with the best business books on strategy, leadership, and economics.', 'Non-Fiction', 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=1000', 'private'),
    ('The Thriller Lounge', 'Edge-of-your-seat mysteries and thrillers. Not for the faint of heart.', 'Fiction', 'https://images.unsplash.com/photo-1508163223045-1880bc36e222?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Mind & Matter', 'Books on psychology, philosophy, and understanding the human condition.', 'Science', 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Accra Readers Circle', 'Connecting readers in Accra through shared stories and monthly meetups.', 'Fiction', 'https://images.unsplash.com/photo-1526243741027-cdbe71e72d38?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Digital Nomads Book Club', 'Books for the remote worker, the traveler, and the global citizen.', 'Non-Fiction', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('The Young Adult Hub', 'YA novels aren''t just for teens. We discuss the best in coming-of-age literature.', 'Fiction', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Climate & Environment', 'Understanding our changing world through science and nature writing.', 'Science', 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('The Biography Shelf', 'Lives well lived. We read one biography or memoir every month.', 'History', 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Nairobi Fiction', 'Exploring the literary scene of East Africa and beyond.', 'Fiction', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Cookbook & Culture', 'We read cookbooks, discuss food culture, and try recipes together.', 'Non-Fiction', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('Startup Founders', 'A closed group for founders to discuss high-growth tactics and startup journeys.', 'Non-Fiction', 'https://images.unsplash.com/photo-1559136555-930b7e47e61d?auto=format&fit=crop&q=80&w=1000', 'private'),
    ('Modern Philosophy', 'Making sense of the modern world through the lens of contemporary philosophy.', 'Non-Fiction', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=1000', 'public'),
    ('The Late Night Readers', 'For those who read when the world sleeps. Eclectic and open-minded.', 'Fiction', 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&q=80&w=1000', 'public');
  END IF;
END $$;